### ISSUE TITLE
Add a webhook by setting up a basic CI/CD process using Travis CI and AWS

### ISSUE THREAD

**Issue by olivervaz** [olivervaz/homepage#34]
S3 bucket names are globally unique. This means that if someone else has a bucket of a certain name, you cannot have a bucket with that same name
Create .travis.yml:
```
language: node_js
node_js:
  - 11.13.0
script:
  - npm install --global workbox-cli
  - workbox generateSW workbox-config.js
deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: ________-staging
    region: eu-central-1
    acl: public_read
    on:
      branch: develop
  - provider: s3
    skip_cleanup: true
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: ________-production
    region: eu-central-1
    acl: public_read
    on:
      branch: master
```
Add your first integration by subscribing to Zeit Now

Execute sudo npm install --global --unsafe-perm now
Create now.json:
```
{
  "name": "homepage"
}
```
Run now to deploy the project
Head over to Zeit Now Dashboard, delete the project, and try to deploy again using Now for GitHub this time
